import styles from "@/styles/about/About.module.css";
import profilePic from "/public/profile.jpg";
import linkedin from "/public/linkedin.svg";
import github from "/public/github.svg";
import Image from "next/image";
import Head from "next/head";
import Skills from "./skills";
import AboutMe from "./aboutme";
import PersonalInfo from "./personalinfo";
import SwitchButton from "./switchbutton";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.socialContainer}>
          <div className={styles.socialDiv}>
            <Image
              src={profilePic}
              alt="Profile"
              className={styles.profilePicture}
            />
            <h3>ROBIN SVENSSON</h3>
            <p>Full Stack Developer</p>
            <div className={styles.socialIcons}>
              <a
                href="https://www.linkedin.com/in/robin-svensson-701366151/"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={linkedin}
                  alt="Twitter"
                  className={styles.socialIcon}
                />
              </a>
              <a
                href="https://www.github.com/rynosuki/"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={github}
                  alt="Github"
                  className={styles.socialIcon}
                />
              </a>
            </div>
          </div>
          <div className={styles.downloadCV}>
            <button className={styles.downloadButton}>DOWNLOAD CV</button>
          </div>
        </div>

        <div>
          <AboutMe />
          <div className={styles.infoContainer}>
            <PersonalInfo />
            <hr></hr>
            <SwitchButton />
            <Skills />
          </div>
        </div>
      </main>
    </>
  );
}
