import styles from "@/styles/about/About.module.css";
import Head from "next/head";
import Skills from "./skills";
import AboutMe from "./aboutme";
import PersonalInfo from "./personalinfo";
import SwitchButton from "./switchbutton";
import Socials from "./socials";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Socials />

        <div>
          <AboutMe />
          <div className={styles.infoContainer}>
            <PersonalInfo />
            <hr></hr>
            <SwitchButton />
            <Skills />
          </div>
        </div>
      </main>
    </>
  );
}
